# Generated by Django 5.1.4 on 2024-12-28 11:00

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Graduate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('profile_picture', models.ImageField(upload_to='profile_pictures')),
                ('address', models.CharField(max_length=255)),
                ('institution', models.CharField(max_length=255)),
                ('course_studied', models.CharField(max_length=255)),
                ('year_of_graduation', models.DateField()),
                ('degrees_obtained', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('BSc', 'BSc'), ('OND', 'OND'), ('HND', 'HND'), ('CERTIFICATE', 'CERTIFICATE'), ('SSCE', 'SSCE')], max_length=225), blank=True, default=list, size=None)),
                ('skills', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=255)),
                ('aspirations', models.CharField(max_length=255)),
                ('preffered_job', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Cosmetics/Skin Care', 'Cosmetics/Skin Care'), ('Pharmacy/Consumables/Surgicals', 'Pharmacy/Consumables/Surgicals'), ('Electronics/Electricals', 'Electronics/Electricals'), ('Clothings/Boutiques', 'Clothings/Boutiques'), ('BuildingMaterials', 'BuildingMaterials'), ('Computers/Phones/Accessories/Software', 'Computers/Phones/Accessories/Software'), ('FoodStores/Drinks/Wines', 'FoodStores/Drinks/Wines'), ('SpareParts and Automobiles', 'SpareParts and Automobiles')], max_length=225), blank=True, default=list, size=None)),
                ('relocate', models.CharField(max_length=255)),
                ('cv', models.FileField(upload_to='cv')),
                ('relocation_availability', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('reference', models.CharField(max_length=255)),
                ('reference_phone_number', models.CharField(max_length=15)),
                ('reference_relationship', models.CharField(max_length=225)),
                ('reference_1', models.CharField(max_length=255)),
                ('reference_phone_number_1', models.CharField(max_length=15)),
                ('reference_relationship_1', models.CharField(max_length=225)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='graduate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
