# Generated by Django 5.1.4 on 2024-12-31 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_is_verified_customuser_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='otp',
        ),
    ]
