# Generated by Django 5.1.4 on 2024-12-31 16:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_graduate_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graduate',
            name='cv',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default.jpg', max_length=255, verbose_name='cv'),
        ),
        migrations.AlterField(
            model_name='graduate',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default.jpg', max_length=255, verbose_name='profile_pictures'),
        ),
    ]
