# Generated by Django 5.1.4 on 2024-12-31 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_graduate_cv_alter_graduate_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graduate',
            name='profile_picture',
        ),
    ]
