# Generated by Django 5.1.4 on 2024-12-31 18:59

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_graduate_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(default='profile_pictures/default.jpg', max_length=255, verbose_name='profile_pictures'),
        ),
    ]
